### ISSUE TITLE
Segfault in ctrl/src/stv.c:copyBios

### ISSUE THREAD

**Issue by pstef** [FCare/Kronos#1579]
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x0000ffffd7280820 in copyBios (zip=0xaaaaac995380, id=0xffffffffb300) at ../ctrl/src/stv.c:2529
2529        while(availableGames[gameId].entry->blobs[i].type != GAME_END) {
(gdb) bt
#0  0x0000ffffd7280820 in copyBios (zip=0xaaaaac995380, id=0xffffffffb300) at ../ctrl/src/stv.c:2529
#1  0x0000ffffd7280380 in processBios (zip=0xaaaaac995380, input=0xffffffffb300) at ../ctrl/src/stv.c:2450
#2  0x0000ffffd72813c4 in recordCallback (zip=0xaaaaac995380, idx=0, header=0xffffffffb290, filename=0xffffd7adf7e0 <jzBuffer> "epr-17740.ic8", user_data=0xffffffffb300)
    at ../ctrl/src/stv.c:2675
#3  0x0000ffffd723d84c in jzReadCentralDirectory (zip=0xaaaaac995380, endRecord=0xffffffffb310, callback=0xffffd728130c <recordCallback>, user_data=0xffffffffb300)
    at ../tools/junzip/junzip.c:110
#4  0x0000ffffd7281980 in loadBios (id=0) at ../ctrl/src/stv.c:2794
#5  0x0000ffffd7281b3c in loadGame (romset=0x0) at ../ctrl/src/stv.c:2835
#6  0x0000ffffd7282598 in STVSingleInit (gamepath=0xffffdd6f8080 <disk_paths> "/game.chd",
    biospath=0xffffdd6f3f78 <stv_bios_path> "/bios/kronos/stvbios.zip", eepromdir=0xffffdd6f5f78 <eeprom_dir> "/saves/Kronos/kronos/stv/",
    favorite_region=1) at ../ctrl/src/stv.c:3050
#7  0x0000ffffd7530aac in YabauseFullInit (init=0xffffdd6efe60 <yinit>) at ../ctrl/src/yabause.c:401
#8  0x0000ffffd75312b4 in YabauseInit (init=0xffffdd6efe60 <yinit>) at ../ctrl/src/yabause.c:628
#9  0x0000ffffd75702b8 in context_reset () at libretro.c:777
#10 0x0000aaaaaab4b6d0 in drivers_init ()
#11 0x0000aaaaaab4ce28 in retroarch_main_init ()
#12 0x0000aaaaaac54838 in content_load ()
#13 0x0000aaaaaac55c80 in task_load_content_internal.constprop ()
#14 0x0000aaaaaab4c528 in rarch_main ()
#15 0x0000fffff305229c in ?? () from /lib/aarch64-linux-gnu/libc.so.6
#16 0x0000fffff305237c in __libc_start_main () from /lib/aarch64-linux-gnu/libc.so.6
#17 0x0000aaaaaab40330 in _start ()
```
Paths redacted.
Let me know if you need anything more than this info.

**Comment by aitorciki** [comment]
Getting the same segmentation fault on my own build (58352d6dc) on Windows 11 (MSYS2) when launching Saturn games. ST-V bios is available in the expected directory, and libretro's own Kronos (old) build runs without issue.

**Comment by aitorciki** [comment]
I can't reproduce as of 4cd7e217d4e3c29366cb97151fc37b78fd0c49fe, my libretro build now runs Saturn and ST-V roms as expected.
