### ISSUE TITLE
[Athlete Kings] Debug AddressSanitizer

### ISSUE THREAD

**Issue by barbudreadmon** [FCare/Kronos#495]
Il semble qu'il y ait en effet des soucis en mémoire : 
```
=================================================================
==27607==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d0000d3440 at pc 0x7f88c24ee913 bp 0x7ffe3eef98d0 sp 0x7ffe3eef98c0
READ of size 4 at 0x61d0000d3440 thread T0
    #0 0x7f88c24ee912 in Vdp2CheckWindow ../vidogl.c:1371
    #1 0x7f88c24ee912 in Vdp2CheckWindowRange ../vidogl.c:1404
    #2 0x7f88c24edcba in Vdp2DrawPatternPos ../vidogl.c:2104
    #3 0x7f88c24eac64 in Vdp2DrawMapTest ../vidogl.c:2560
    #4 0x7f88c24cd775 in Vdp2DrawNBG2 ../vidogl.c:6302
    #5 0x7f88c24aaa87 in VIDOGLVdp2DrawScreens ../vidogl.c:6764
    #6 0x7f88c2464641 in VIDOGLVdp2Draw ../vidogl.c:5240
    #7 0x7f88c259898c in Vdp2VBlankIN ../vdp2.c:461
    #8 0x7f88c264b1d0 in YabauseEmulate ../yabause.c:916
    #9 0x7f88c264a976 in YabauseExec ../yabause.c:757
    #10 0x7f88c2660979 in retro_run /home/barbu/KronosCurrent/yabause/src/libretro/libretro.c:1469
    #11 0x55fddfd071dc  (/usr/bin/retroarch+0x5f1dc)
    #12 0x55fddfd0c35b  (/usr/bin/retroarch+0x6435b)
    #13 0x55fddfd05f0f  (/usr/bin/retroarch+0x5df0f)
    #14 0x7f88df34f79a in __libc_start_main (/lib64/libc.so.6+0x2379a)
    #15 0x55fddfd03029  (/usr/bin/retroarch+0x5b029)

0x61d0000d3440 is located 64 bytes to the left of 2048-byte region [0x61d0000d3480,0x61d0000d3c80)
allocated by thread T0 here:
    #0 0x7f88e506dda0 in __interceptor_malloc /var/tmp/portage/sys-devel/gcc-8.2.0-r6/work/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x7f88c255d4e4 in YglGetWindowPointer ../ygles.c:3794
    #2 0x7f88c24829e3 in Vdp2GenerateWindowInfo ../vidogl.c:1291
    #3 0x7f88c254ec2d in YglSetVdp2Window ../ygles.c:2886
    #4 0x7f88c2556bef in YglRender ../ygles.c:3420
    #5 0x7f88c24ad284 in waitVdp2DrawScreensEnd ../vidogl.c:6830
    #6 0x7f88c2598f25 in Vdp2HBlankIN ../vdp2.c:491
    #7 0x7f88c264af9a in YabauseEmulate ../yabause.c:890
    #8 0x7f88c264a976 in YabauseExec ../yabause.c:757
    #9 0x7f88c2660979 in retro_run /home/barbu/KronosCurrent/yabause/src/libretro/libretro.c:1469
    #10 0x55fddfd071dc  (/usr/bin/retroarch+0x5f1dc)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../vidogl.c:1371 in Vdp2CheckWindow
Shadow bytes around the buggy address:
  0x0c3a80012630: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a80012640: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a80012650: 00 00 07 fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a80012660: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a80012670: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c3a80012680: fa fa fa fa fa fa fa fa[fa]fa fa fa fa fa fa fa
  0x0c3a80012690: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a800126a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a800126b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a800126c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a800126d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==27607==ABORTING
```

Par contre ce n'est pas le seul jeu affecté, avec Shining Force 3 : 
```
=================================================================
==27500==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d0000d3e60 at pc 0x7fd3256efdc1 bp 0x7fffd5a726f0 sp 0x7fffd5a726e0
READ of size 4 at 0x61d0000d3e60 thread T0
    #0 0x7fd3256efdc0 in Vdp2CheckWindow ../vidogl.c:1371
    #1 0x7fd3256efdc0 in Vdp2CheckWindowRange ../vidogl.c:1412
    #2 0x7fd3256edcba in Vdp2DrawPatternPos ../vidogl.c:2104
    #3 0x7fd3256eac64 in Vdp2DrawMapTest ../vidogl.c:2560
    #4 0x7fd3256dd062 in Vdp2DrawNBG0 ../vidogl.c:5977
    #5 0x7fd3256aaa9f in VIDOGLVdp2DrawScreens ../vidogl.c:6768
    #6 0x7fd325664641 in VIDOGLVdp2Draw ../vidogl.c:5240
    #7 0x7fd32579898c in Vdp2VBlankIN ../vdp2.c:461
    #8 0x7fd32584b1d0 in YabauseEmulate ../yabause.c:916
    #9 0x7fd32584a976 in YabauseExec ../yabause.c:757
    #10 0x7fd325860979 in retro_run /home/barbu/KronosCurrent/yabause/src/libretro/libretro.c:1469
    #11 0x564c9f6231dc  (/usr/bin/retroarch+0x5f1dc)
    #12 0x564c9f62835b  (/usr/bin/retroarch+0x6435b)
    #13 0x564c9f621f0f  (/usr/bin/retroarch+0x5df0f)
    #14 0x7fd34252e79a in __libc_start_main (/lib64/libc.so.6+0x2379a)
    #15 0x564c9f61f029  (/usr/bin/retroarch+0x5b029)

0x61d0000d3e60 is located 32 bytes to the left of 2048-byte region [0x61d0000d3e80,0x61d0000d4680)
allocated by thread T0 here:
    #0 0x7fd34824cda0 in __interceptor_malloc /var/tmp/portage/sys-devel/gcc-8.2.0-r6/work/gcc-8.2.0/libsanitizer/asan/asan_malloc_linux.cc:86
    #1 0x7fd32575d4e4 in YglGetWindowPointer ../ygles.c:3794
    #2 0x7fd3256829ed in Vdp2GenerateWindowInfo ../vidogl.c:1292
    #3 0x7fd32574ec2d in YglSetVdp2Window ../ygles.c:2886
    #4 0x7fd325756bef in YglRender ../ygles.c:3420
    #5 0x7fd3256ad284 in waitVdp2DrawScreensEnd ../vidogl.c:6830
    #6 0x7fd325798f25 in Vdp2HBlankIN ../vdp2.c:491
    #7 0x7fd32584af9a in YabauseEmulate ../yabause.c:890
    #8 0x7fd32584a976 in YabauseExec ../yabause.c:757
    #9 0x7fd325860979 in retro_run /home/barbu/KronosCurrent/yabause/src/libretro/libretro.c:1469
    #10 0x564c9f6231dc  (/usr/bin/retroarch+0x5f1dc)

SUMMARY: AddressSanitizer: heap-buffer-overflow ../vidogl.c:1371 in Vdp2CheckWindow
Shadow bytes around the buggy address:
  0x0c3a80012770: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a80012780: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a80012790: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a800127a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3a800127b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c3a800127c0: fa fa fa fa fa fa fa fa fa fa fa fa[fa]fa fa fa
  0x0c3a800127d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a800127e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a800127f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a80012800: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3a80012810: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==27500==ABORTING
```

Si je réussis à comprendre ces messages d'erreur, je fais signe xD

**Comment by barbudreadmon** [comment]
Erreur corrigé, mais çà ne semble pas être lié à l'explosion de la mémoire.
