### ISSUE TITLE
Erreur de segmentation

### ISSUE THREAD

**Issue by ghost** [FCare/Kronos#91]
Bonjour,

Sous Manjaro, quand je change des paramètres j'ai une erreur de segmentation (core dumped) et Yabause se ferme.

**Comment by FCare** [comment]
Bonjour,

Quel parametres? Sous QT?
Pouvez-vous me donner la trace de gdb? 
gdb --args src/qt/yabause, puis tapez r et une fois le Segfault atteint, tapez bt.

Merci

**Comment by ghost** [comment]
Merci pour ta réponse.

Alors oui, c'est qt. Yabause plante quand je ferme les settings, quoi que je fasse.

Voici ce que j'obtiens : 

```
Thread 1 "yabause" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in  ()
#1  0x00000000005cf682 in YglTMInit ()
#2  0x00000000005cfc0e in YglInit ()
#3  0x00000000005814f3 in VIDOGLInit ()
#4  0x000000000056dd4a in VideoInit ()
#5  0x00000000005a3b51 in YabauseInit ()
#6  0x0000000000518660 in YabauseThread::initEmulation() ()
#7  0x0000000000518753 in YabauseThread::pauseEmulation(bool, bool) ()
#8  0x00000000004a6310 in UIYabause::on_aFileSettings_triggered() ()
#9  0x000000000052118d in UIYabause::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
#10 0x00000000005215a4 in UIYabause::qt_metacall(QMetaObject::Call, int, void**) ()
#11 0x00007ffff4098fb2 in QMetaObject::activate(QObject*, int, int, void**) ()
    at /usr/lib/libQt5Core.so.5
#12 0x00007ffff5167383 in QAction::triggered(bool) ()
    at /usr/lib/libQt5Widgets.so.5
#13 0x00007ffff5169c06 in QAction::activate(QAction::ActionEvent) ()
    at /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff52efc45 in  () at /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff52f730c in  () at /usr/lib/libQt5Widgets.so.5
#16 0x00007ffff52f8174 in QMenu::mouseReleaseEvent(QMouseEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---
#17 0x00007ffff51ade38 in QWidget::event(QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#18 0x00007ffff52fa4ac in QMenu::event(QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#19 0x00007ffff516de3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#20 0x00007ffff5175d91 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#21 0x00007ffff40686c0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#22 0x00007ffff5174d1a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
    at /usr/lib/libQt5Widgets.so.5
#23 0x00007ffff51c8fb7 in  () at /usr/lib/libQt5Widgets.so.5
#24 0x00007ffff51cb9a0 in  () at /usr/lib/libQt5Widgets.so.5
#25 0x00007ffff516de3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
#26 0x00007ffff5175816 in QApplication::notify(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#27 0x00007ffff40686c0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#28 0x00007ffff4964634 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /usr/lib/libQt5Gui.so.5
---Type <return> to continue, or q <return> to quit---
#29 0x00007ffff4966186 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /usr/lib/libQt5Gui.so.5
#30 0x00007ffff493dbbc in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Gui.so.5
#31 0x00007fffeaac72fd in  () at /usr/lib/libQt5XcbQpa.so.5
#32 0x00007ffff4066d0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#33 0x00007ffff406fff8 in QCoreApplication::exec() ()
    at /usr/lib/libQt5Core.so.5
#34 0x000000000049949c in main ()

```

**Comment by FCare** [comment]
Ca doit etre lié au driver de ta carte graphique. Tu as quoi comme carte et quel est ton driver?
Les drivers supportent OpenGLES3?

**Comment by BenjaminSiskoo** [comment]
Par curiosité test ca : 

1) dans ton répertoire Yabause (là où se trouve les dll, yabause§.exe, etc...), mets le fichier yabause.ini.
2) Ouvre le et s'il n'est pas vide,, supprime tout.
3) Enregistre le.
4) Lance, yabause, reconfigure le avec tes paramètres. 

As tu le même problème ?

**Comment by ghost** [comment]
Merci Benjamin pour ton aide, mais cela ne change rien.
Il y a peut-être un bug avec le pilote nvidia et opengles d'après des éléments que j'ai trouvés. Je vais attendre la mise à jour de manjaro car le pilote utilisé par cette distribution n'est actuellement pas la dernière version stable.

**Comment by BenjaminSiskoo** [comment]
Ok pas de soucis, l'ini est parfois sensible. J'espère que le pilote corrigera ton problème :)

**Comment by ghost** [comment]
Bon toujours rien, malgré une mise à jour du pilote nvidia. Les jeux ne démarrent pas non plus.
